# Activamos el perfil de desarrollo por defecto
spring:
  application:
      name: gdmerp-backend
  profiles:
    active: dev

# Configuraciones globales (comunes para cualquier entorno)
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true