-- GdmERP - Sesión 4: Tabla de Detalle de Orden de Producción (Cabecera-Detalle)
-- Ejecutar con un usuario con privilegios DBA sobre el esquema GDM_PRODUCCION.

CREATE TABLE GDM_PRODUCCION.DETALLES_ORDEN_PRODUCCION (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDEN_ID NUMBER NOT NULL,
    PRODUCTO_ID NUMBER NOT NULL,
    NOMBRE_PRODUCTO VARCHAR2(120) NOT NULL,
    CANTIDAD_REQUERIDA NUMBER NOT NULL,
    CONSTRAINT FK_DET_ORD FOREIGN KEY (ORDEN_ID) REFERENCES GDM_PRODUCCION.ORDENES_PRODUCCION(ID)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON GDM_PRODUCCION.DETALLES_ORDEN_PRODUCCION TO GDMERP_APP;