server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://gdmerp-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: gdmerp-backend
    static_configs:
      - targets: [localhost]
        labels:
          application: gdmerp-backend
          __path__: /var/log/gdmerp-backend/*.log